# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.sort_by import SortBy  # noqa: E501

class TestSortBy(unittest.TestCase):
    """SortBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortBy(self):
        """Test SortBy"""
        # inst = SortBy()

if __name__ == '__main__':
    unittest.main()
