# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_get_all_available_entities_of_a_theme_gazettes_by_theme_entities_theme_get(self) -> None:
        """Test case for get_all_available_entities_of_a_theme_gazettes_by_theme_entities_theme_get

        Get All Available Entities Of A Theme  # noqa: E501
        """
        pass

    def test_get_all_available_subthemes_of_a_theme_gazettes_by_theme_subthemes_theme_get(self) -> None:
        """Test case for get_all_available_subthemes_of_a_theme_gazettes_by_theme_subthemes_theme_get

        Get All Available Subthemes Of A Theme  # noqa: E501
        """
        pass

    def test_get_all_available_themes_gazettes_by_theme_themes_get(self) -> None:
        """Test case for get_all_available_themes_gazettes_by_theme_themes_get

        Get All Available Themes  # noqa: E501
        """
        pass

    def test_get_city_by_ibgeid_cities_territory_id_get(self) -> None:
        """Test case for get_city_by_ibgeid_cities_territory_id_get

        Get City By Ibge Id  # noqa: E501
        """
        pass

    def test_get_company_info_by_cnpj_number_company_info_cnpj_get(self) -> None:
        """Test case for get_company_info_by_cnpj_number_company_info_cnpj_get

        Get Company Info By Cnpj Number  # noqa: E501
        """
        pass

    def test_get_company_partners_infos_by_cnpj_number_company_partners_cnpj_get(self) -> None:
        """Test case for get_company_partners_infos_by_cnpj_number_company_partners_cnpj_get

        Get Company Partners Infos By Cnpj Number  # noqa: E501
        """
        pass

    def test_search_for_cities_by_name_cities_get(self) -> None:
        """Test case for search_for_cities_by_name_cities_get

        Search For Cities By Name.  # noqa: E501
        """
        pass

    def test_search_for_content_in_gazette_excerpts_associated_with_a_theme_gazettes_by_theme_theme_get(self) -> None:
        """Test case for search_for_content_in_gazette_excerpts_associated_with_a_theme_gazettes_by_theme_theme_get

        Search For Content In Gazette Excerpts Associated With A Theme  # noqa: E501
        """
        pass

    def test_search_for_content_in_gazettes_gazettes_get(self) -> None:
        """Test case for search_for_content_in_gazettes_gazettes_get

        Search For Content In Gazettes  # noqa: E501
        """
        pass

    def test_send_a_suggestion_suggestions_post(self) -> None:
        """Test case for send_a_suggestion_suggestions_post

        Send A Suggestion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
