# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.partners_search_response import PartnersSearchResponse  # noqa: E501

class TestPartnersSearchResponse(unittest.TestCase):
    """PartnersSearchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartnersSearchResponse:
        """Test PartnersSearchResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PartnersSearchResponse`
        """
        model = PartnersSearchResponse()  # noqa: E501
        if include_optional:
            return PartnersSearchResponse(
                total_partners = 56,
                partners = [
                    openapi_client.models.partner.Partner(
                        cnpj_basico = '', 
                        cnpj_ordem = '', 
                        cnpj_dv = '', 
                        cnpj_completo = '', 
                        cnpj_completo_apenas_numeros = '', 
                        identificador_socio = '', 
                        razao_social = '', 
                        cnpj_cpf_socio = '', 
                        qualificacao_socio = '', 
                        data_entrada_sociedade = '', 
                        pais_socio_estrangeiro = '', 
                        numero_cpf_representante_legal = '', 
                        nome_representante_legal = '', 
                        qualificacao_representante_legal = '', 
                        faixa_etaria = '', )
                    ]
            )
        else:
            return PartnersSearchResponse(
                total_partners = 56,
                partners = [
                    openapi_client.models.partner.Partner(
                        cnpj_basico = '', 
                        cnpj_ordem = '', 
                        cnpj_dv = '', 
                        cnpj_completo = '', 
                        cnpj_completo_apenas_numeros = '', 
                        identificador_socio = '', 
                        razao_social = '', 
                        cnpj_cpf_socio = '', 
                        qualificacao_socio = '', 
                        data_entrada_sociedade = '', 
                        pais_socio_estrangeiro = '', 
                        numero_cpf_representante_legal = '', 
                        nome_representante_legal = '', 
                        qualificacao_representante_legal = '', 
                        faixa_etaria = '', )
                    ],
        )
        """

    def testPartnersSearchResponse(self):
        """Test PartnersSearchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
