# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.city_level import CityLevel  # noqa: E501

class TestCityLevel(unittest.TestCase):
    """CityLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCityLevel(self):
        """Test CityLevel"""
        # inst = CityLevel()

if __name__ == '__main__':
    unittest.main()
