# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.gazette_item import GazetteItem  # noqa: E501

class TestGazetteItem(unittest.TestCase):
    """GazetteItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GazetteItem:
        """Test GazetteItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GazetteItem`
        """
        model = GazetteItem()  # noqa: E501
        if include_optional:
            return GazetteItem(
                territory_id = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                scraped_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                url = '',
                territory_name = '',
                state_code = '',
                excerpts = [
                    ''
                    ],
                edition = '',
                is_extra_edition = True,
                txt_url = ''
            )
        else:
            return GazetteItem(
                territory_id = '',
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                scraped_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                url = '',
                territory_name = '',
                state_code = '',
                excerpts = [
                    ''
                    ],
        )
        """

    def testGazetteItem(self):
        """Test GazetteItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
