# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class CityLevel(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    EMPTY = ''
    ENUM_0 = '0'
    ENUM_1 = '1'
    ENUM_2 = '2'
    ENUM_3 = '3'

    @classmethod
    def from_json(cls, json_str: str) -> CityLevel:
        """Create an instance of CityLevel from a JSON string"""
        return CityLevel(json.loads(json_str))


