# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.city import City

class CitySearchResponse(BaseModel):
    """
    CitySearchResponse
    """
    city: City = Field(...)
    __properties = ["city"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CitySearchResponse:
        """Create an instance of CitySearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of city
        if self.city:
            _dict['city'] = self.city.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CitySearchResponse:
        """Create an instance of CitySearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CitySearchResponse.parse_obj(obj)

        _obj = CitySearchResponse.parse_obj({
            "city": City.from_dict(obj.get("city")) if obj.get("city") is not None else None
        })
        return _obj


