# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field
from openapi_client.models.company import Company

class CompanySearchResponse(BaseModel):
    """
    CompanySearchResponse
    """
    cnpj_info: Company = Field(...)
    __properties = ["cnpj_info"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CompanySearchResponse:
        """Create an instance of CompanySearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of cnpj_info
        if self.cnpj_info:
            _dict['cnpj_info'] = self.cnpj_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CompanySearchResponse:
        """Create an instance of CompanySearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CompanySearchResponse.parse_obj(obj)

        _obj = CompanySearchResponse.parse_obj({
            "cnpj_info": Company.from_dict(obj.get("cnpj_info")) if obj.get("cnpj_info") is not None else None
        })
        return _obj


