# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, conlist
from openapi_client.models.gazette_item import GazetteItem

class GazetteSearchResponse(BaseModel):
    """
    GazetteSearchResponse
    """
    total_gazettes: StrictInt = Field(...)
    gazettes: conlist(GazetteItem) = Field(...)
    __properties = ["total_gazettes", "gazettes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GazetteSearchResponse:
        """Create an instance of GazetteSearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in gazettes (list)
        _items = []
        if self.gazettes:
            for _item in self.gazettes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['gazettes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GazetteSearchResponse:
        """Create an instance of GazetteSearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GazetteSearchResponse.parse_obj(obj)

        _obj = GazetteSearchResponse.parse_obj({
            "total_gazettes": obj.get("total_gazettes"),
            "gazettes": [GazetteItem.from_dict(_item) for _item in obj.get("gazettes")] if obj.get("gazettes") is not None else None
        })
        return _obj


