# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, conlist
from openapi_client.models.partner import Partner

class PartnersSearchResponse(BaseModel):
    """
    PartnersSearchResponse
    """
    total_partners: StrictInt = Field(...)
    partners: conlist(Partner) = Field(...)
    __properties = ["total_partners", "partners"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PartnersSearchResponse:
        """Create an instance of PartnersSearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in partners (list)
        _items = []
        if self.partners:
            for _item in self.partners:
                if _item:
                    _items.append(_item.to_dict())
            _dict['partners'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PartnersSearchResponse:
        """Create an instance of PartnersSearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PartnersSearchResponse.parse_obj(obj)

        _obj = PartnersSearchResponse.parse_obj({
            "total_partners": obj.get("total_partners"),
            "partners": [Partner.from_dict(_item) for _item in obj.get("partners")] if obj.get("partners") is not None else None
        })
        return _obj


