# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SortBy(str, Enum):
    """
    An enumeration.
    """

    """
    allowed enum values
    """
    RELEVANCE = 'relevance'
    DESCENDING_DATE = 'descending_date'
    ASCENDING_DATE = 'ascending_date'

    @classmethod
    def from_json(cls, json_str: str) -> SortBy:
        """Create an instance of SortBy from a JSON string"""
        return SortBy(json.loads(json_str))


