# coding: utf-8

"""
    Querido Diário

    API to access the gazettes from all Brazilian cities

    The version of the OpenAPI document: 0.17.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, StrictInt, conlist
from openapi_client.models.themed_excerpt_item import ThemedExcerptItem

class ThemedExcerptSearchResponse(BaseModel):
    """
    ThemedExcerptSearchResponse
    """
    total_excerpts: StrictInt = Field(...)
    excerpts: conlist(ThemedExcerptItem) = Field(...)
    __properties = ["total_excerpts", "excerpts"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ThemedExcerptSearchResponse:
        """Create an instance of ThemedExcerptSearchResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in excerpts (list)
        _items = []
        if self.excerpts:
            for _item in self.excerpts:
                if _item:
                    _items.append(_item.to_dict())
            _dict['excerpts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ThemedExcerptSearchResponse:
        """Create an instance of ThemedExcerptSearchResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ThemedExcerptSearchResponse.parse_obj(obj)

        _obj = ThemedExcerptSearchResponse.parse_obj({
            "total_excerpts": obj.get("total_excerpts"),
            "excerpts": [ThemedExcerptItem.from_dict(_item) for _item in obj.get("excerpts")] if obj.get("excerpts") is not None else None
        })
        return _obj


